module.exports = {
	'Main Menu': {
		link: '/Main Menu',
		title: "Main Menu",
		name: "Main Menu",
		buttons: [
			'Display Transaction',
			'Merchant Settings',
			'Operation Settings',
			'Host Settings',
			'System Settings',
			'Communication',
		],
	},
	'Display Transaction': {
		back: '/Main Menu',
		link: '/Display Transaction',
		name: 'Display Transaction',
		title: 'Display Transaction',
		buttons: [
			'Review',
			'Find'
		],
	},
	'Review': {
		back: '/Display Transaction',
		forward: '/Review Totals',
		link: '/Review',
		name: 'Review',
		title: 'Password',
		password: '123456',
	},
	'Review Totals': {
		back: '/Display Transaction',
		link: '/Review Totals',
		name: 'Review Totals',
		title: 'Totals (0)',
		varButtons: [
			'CREDIT(0)    $0.00',
			'DEBIT(0)    $0.00',
			'EBT(0)    $0.00',
			'GIFT(0)    $0.00',
			'LOYALTY(0)    $0.00',
		],
		varButtonOptions: [
			'Review Totals',
			'Review Totals',
			'Review Totals',
			'Review Totals',
			'Review Totals',
		],
	},
	'Find': {
		back: '/Display Transaction',
		forward: '/Find Options',
		link: '/Find',
		name: 'Find',
		title: 'Password',
		password: '123456',
	},
	'Find Options': {
		back: '/Display Transaction',
		forward: '/Display Transaction',
		link: '/Find Options', 
		name: 'Find Options', 
		title: 'Please Enter Last 4 Digits',
		password: '1234',
	},
	'Merchant Settings': {
		back: '/Main Menu',
		link: '/Merchant Settings',
		name: 'Merchant Settings',
		title: 'Merchant Parameters',
		buttons: [
			'Authorizations',
		]
	},
	'Authorizations': {
		back: '/Merchant Settings',
		forward: '/Authorizations Options',
		link: '/Authorizations',
		name: 'Authorizations',
		title: 'Password',
		password: '123456',
	},
	'Authorizations Options': {
		back: '/Merchant Settings',
		link: '/Authorizations Options',
		name: 'Authorizations Options',
		title: 'Authorizations',
		buttons: [
			'Transaction Types',
		],
	},
	'Transaction Types': {
		back: '/Authorizations Options',
		link: '/Transaction Types',
		name: 'Transaction Types',
		title: 'Please Select Payment Method',
		buttons: [
			'CREDIT',
			'DEBIT',
			'EBT',
			'GIFT',
			'LOYALATY',
		],
	},
	'CREDIT': {
		back: '/Transaction Types',
		link: '/CREDIT',
		name: 'CREDIT',
		title: 'CREDIT',
		next: 'CREDIT2',
		buttons: [
			'AUTH',
			'POSTAUTH',
			'FORCED',
			'RETURN',
			'VERIFY',
			'TOKENIZE',
		],
	},
	'CREDIT2': {
		back: '/Transaction Types',
		link: '/CREDIT2',
		name: 'CREDIT2',
		title: 'CREDIT',
		prev: 'CREDIT',
		buttons: [
			'BALANCE',
			'V/SALE',
			'V/AUTH',
			'V/POST',
			'V/FRCD',
			'V/RTRN',
		],
	},
	'DEBIT': {
		back: '/Transaction Types',
		link: '/DEBIT',
		name: 'DEBIT',
		title: 'DEBIT',
		buttons: [
			'RETURN',
			'V/SALE',
		],
	},
	'EBT': {
		back: '/Transaction Types',
		link: '/EBT',
		name: 'EBT',
		title: 'EBT',
		buttons: [
			'RETURN',
			'WITHDRAWAL',
			'BALANCE',
		],
	},
	'GIFT': {
		back: '/Transaction Types',
		link: '/GIFT',
		name: 'GIFT',
		title: 'GIFT',
		buttons: [
			'ADD',
			'ACTIVATE',
			'REPLACE',
			'BALANCE',
			'VOID',
			'DEACT',
		],
	},
	'LOYALATY': {
		back: '/Transaction Types',
		link: '/LOYALATY',
		name: 'LOYALATY',
		title: 'LOYALATY',
		buttons: [
			'ADD',
			'REPLACE',
			'BALANCE',
			'VOID',
			'DEACT',
		],
	},
	'ACTIVATE': {
		back: '/Transaction Types',
		link: '/ACTIVATE', 
		name: 'ACTIVATE', 
		title: 'CARD-ACTIVATE',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'ADD': {
		back: '/Transaction Types',
		link: '/ADD', 
		name: 'ADD', 
		title: 'CARD-ADD',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'AUTH': {
		back: '/Transaction Types',
		link: '/AUTH', 
		name: 'AUTH', 
		title: 'CARD-AUTH',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'DEACT': {
		back: '/Transaction Types',
		link: '/DEACT', 
		name: 'DEACT', 
		title: 'CARD-DEACT',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'POSTAUTH': {
		back: '/Transaction Types',
		link: '/POSTAUTH', 
		name: 'POSTAUTH', 
		title: 'CARD-POSTAUTH',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'FORCED': {
		back: '/Transaction Types',
		link: '/FORCED', 
		name: 'FORCED', 
		title: 'CARD-FORCED',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'REPLACE': {
		back: '/Transaction Types',
		link: '/REPLACE', 
		name: 'REPLACE', 
		title: 'CARD-REPLACE',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'RETURN': {
		back: '/Transaction Types',
		link: '/RETURN', 
		name: 'RETURN', 
		title: 'CARD-RETURN',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'VERIFY': {
		back: '/Transaction Types',
		link: '/VERIFY', 
		name: 'VERIFY', 
		title: 'CARD-VERIFY',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'VOID': {
		back: '/Transaction Types',
		link: '/VOID', 
		name: 'VOID', 
		title: 'CARD-VOID',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'TOKENIZE': {
		back: '/Transaction Types',
		link: '/TOKENIZE', 
		name: 'TOKENIZE', 
		title: 'CARD-TOKENIZE',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'BALANCE': {
		back: '/Transaction Types',
		link: '/BALANCE', 
		name: 'BALANCE', 
		title: 'CARD-BALANCE',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'WITHDRAWAL': {
		back: '/Transaction Types',
		link: '/WITHDRAWAL', 
		name: 'WITHDRAWAL', 
		title: 'CARD-WITHDRAWAL',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'V/SALE': {
		back: '/Transaction Types',
		link: '/V/SALE', 
		name: 'V/SALE', 
		title: 'CARD-V/SALE',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'V/AUTH': {
		back: '/Transaction Types',
		link: '/V/AUTH', 
		name: 'V/AUTH', 
		title: 'CARD-V/AUTH',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'V/POST': {
		back: '/Transaction Types',
		link: '/V/POST', 
		name: 'V/POST', 
		title: 'CARD-V/POST',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'V/FRCD': {
		back: '/Transaction Types',
		link: '/V/FRCD', 
		name: 'V/FRCD', 
		title: 'CARD-V/FRCD',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'V/RTRN': {
		back: '/Transaction Types',
		link: '/V/RTRN', 
		name: 'V/RTRN', 
		title: 'CARD-V/RTRN',
		varButtons: [
			'Disabled',
			'Always Enabled',
			'Password Protected',
		],
		titleVar: 2,
	},
	'Operation Settings': {
		back: '/Main Menu',
		link: '/Operation Settings',
		name: 'Operation Settings',
		title: 'Operation Settings',
		varButtons: [
			'COMING SOON',
		],
	},
	'Host Settings': {
		back: '/Main Menu',
		forward: '/Host Settings Options',
		link: '/Host Settings',
		name: 'Host Settings',
		title: 'Password',
		password: '123456',
	},
	'Host Settings Options': {
		back: '/Main Menu',
		link: '/Host Settings Options',
		name: 'Host Settings Options',
		title: 'Host Settings',
		buttons: [
			'Host Parameters',
		],
	},
	'Host Parameters': {
		back: '/Host Settings Options',
		link: '/Host Parameters',
		name: 'Host Parameters',
		title: 'Host Parameters',
		buttons: [
			'LicenseID',
			'SiteID',
			'DeviceID',
			'UserName',
			'Password',
		],
	},
	'LicenseID': {
		back: '/Host Parameters',
		link: '/LicenseID',
		name: 'LicenseID',
		title: 'License ID',
		input: '100002',
	},
	'SiteID': {
		back: '/Host Parameters',
		link: '/SiteID',
		name: 'SiteID',
		title: 'Site ID',
		input: '100000',
	},
	'DeviceID': {
		back: '/Host Parameters',
		link: '/DeviceID',
		name: 'DeviceID',
		title: 'Device ID',
		input: '2000002',
	},
	'UserName': {
		back: '/Host Parameters',
		link: '/UserName',
		name: 'UserName',
		title: 'UserName',
		input: 'admin',
	},
	'Password': {
		back: '/Host Parameters',
		link: '/Password',
		name: 'Password',
		title: 'Password',
		input: 'test1234',
	},
	'System Settings': {
		back: '/Main Menu',
		link: '/System Settings',
		name: 'System Settings',
		title: 'System Settings',
		varButtons: [
			'COMING SOON',
		],
	},
	'Communication': {
		back: '/Main Menu',
		forward: '/Communication Options',
		link: '/Communication',
		name: 'Communication',
		title: 'Password',
		password: '123456',
	},
	'Communication Options': {
		back: '/Main Menu',
		link: '/Communication Options',
		name: 'Communication Options',
		title: 'Communication Options',
		next: 'Communication Options2',
		buttons: [
			'Main Communication',
			'Backup Comm.',
			'Maximum Tries',
			'Connect Timeout',
			'Receive Timeout',
			'LAN Parameters',
		],
	},
	'Communication Options2': {
		back: '/Main Menu',
		link: '/Communication Options2',
		name: 'Communication Options2',
		title: 'Communication Options',
		prev: 'Communication Options',
		buttons: [
			'ECR Comm. Type',
		],
	},
	'Main Communication': {
		back: '/Communication Options',
		link: '/Main Communication', 
		name: 'Main Communication', 
		title: 'Main Communication',
		varButtons: [
			'LAN',
		],
		titleVar: 1,
	},
	'Backup Comm.': {
		back: '/Communication Options',
		link: '/Backup Comm.', 
		name: 'Backup Comm.', 
		title: 'Backup Communication',
		varButtons: [
			'LAN',
			'Name',
		],
		titleVar: 2,
	},
	'Maximum Tries': {
		back: '/Communication Options',
		link: '/Maximum Tries',
		name: 'Maximum Tries',
		title: 'Maximum Tries',
		input: '1',
	},
	'Connect Timeout': {
		back: '/Communication Options',
		link: '/Connect Timeout',
		name: 'Connect Timeout',
		title: 'Connect Timeout',
		input: '300',
	},
	'Receive Timeout': {
		back: '/Communication Options',
		link: '/Receive Timeout',
		name: 'Receive Timeout',
		title: 'Receive Timeout',
		input: '450',
	},
	'LAN Parameters': {
		back: '/Communication Options',
		link: '/LAN Parameters',
		name: 'LAN Parameters',
		title: 'LAN Parameters',
		next: 'LAN Parameters2',
		buttons: [
			'LAN Type',
			'IP Address',
			'Subnet Mask',
			'Gateway IP',
			'DNS IP',
			'PING',
		],
	},
	'LAN Parameters2': {
		back: '/Communication Options',
		link: '/LAN Parameters2',
		name: 'LAN Parameters2',
		title: 'LAN Parameters',
		prev: 'LAN Parameters',
		buttons: [
			'MAC Address',
		],
	},
	'LAN Type': {
		back: '/LAN Parameters',
		link: '/LAN Type', 
		name: 'LAN Type', 
		title: 'LAN Type',
		varButtons: [
			'DHCP',
			'Static',
		],
		titleVar: 2,
	},
	'IP Address': {
		back: '/LAN Parameters',
		link: '/IP Address',
		name: 'IP Address',
		title: 'IP Address',
		address: '192.168.001.005',
	},
	'Subnet Mask': {
		back: '/LAN Parameters',
		link: '/Subnet Mask',
		name: 'Subnet Mask',
		title: 'Subnet Mask',
		address: '255.255.255.000',
	},
	'Gateway IP': {
		back: '/LAN Parameters',
		link: '/Gateway IP',
		name: 'Gateway IP',
		title: 'Gateway IP',
		address: '192.168.001.001',
	},
	'DNS IP': {
		back: '/LAN Parameters',
		link: '/DNS IP',
		name: 'DNS IP',
		title: 'DNS IP',
		address: '008.008.008.008',
	},
	'PING': {
		back: '/LAN Parameters',
		link: '/PING',
		name: 'PING',
		title: 'Server URL',
		input: 'WWW.GOOGLE.COM',
	},
	'MAC Address': {
		back: '/LAN Parameters',
		link: '/MAC Address',
		name: 'MAC Address',
		title: 'MAC',
		input: '1A5D47S1E6D4',
	},
	'ECR Comm. Type': {
		back: '/Communication Options',
		link: '/ECR Comm. Type', 
		name: 'ECR Comm. Type', 
		title: 'ECR Communication Type',
		varButtons: [
			'COM2',
			'USB',
			'Ethernet',
		],
		varButtonOptions: [
			'/COM2',
			null,
			'/Ethernet',
		],
		titleVar: 3,
	},
	'COM2': {
		back: '/Communication Options',
		link: '/COM2', 
		name: 'COM2', 
		title: 'ECR BaudRate',
		varButtons: [
			'9600',
			'115200',
		],
		titleVar: 1,
	},
	'Ethernet': {
		back: '/Communication Options',
		forward: '/Communication Protocol',
		link: '/Ethernet', 
		name: 'Ethernet', 
		title: 'Communication Port',
		input: '2050',
	},
	'Communication Protocol': {
		back: '/Communication Options',
		link: '/Communication Protocol', 
		name: 'Communication Protocol', 
		title: 'Communication Protocol',
		varButtons: [
			'TCP/IP',
			'HTTP GET',
			'SSL/TLS',
			'HTTPS GET',
		],
		titleVar: 2,
	},
};
